feat: add property based tests for encoding/decoding
grid-x/modbus pull request #33
Opened 2020-12-23 08:36 UTC by jhedev

You can run the individual test with as many checks as possible, e.g.

```
go test -v -run TestTCPEncodeDecode -rapid.checks=10000 # to run 10k checks
```

Currently, everything passes the checks \o/ I introduced small bugs in the logic
of the methods and quickly the tests failed. So they are indeed working :)

Not sure if we want to keep this which is up to the others. IMO it is a nice way
to generate plenty of testcases.

2020-12-23 08:37 UTC, jhedev commented
Oh and by default this will run 100 checks (as you can see in the CI output)

2021-01-12 19:04 UTC, gq0 requested changes
Nice. Can you adjust to go.mod change? And I guess cmp is not needed.

2021-01-12 19:04 UTC, gq0 commented on rtuclient_prop_test.go
> +		if !cmp.Equal(pdu, dpdu) {
Do you really need cmp for this basic comparison? I think using std reflect pkg or just directly comparing the `FunctionCode` and `Data` will work. Just trying to minimise dependencies ;)

2021-01-12 19:04 UTC, gq0 commented on tcpclient_prop_test.go
> +		if !cmp.Equal(pdu, dpdu) {
Same as above.

2021-01-13 07:30 UTC, jhedev commented on rtuclient_prop_test.go
> +		if !cmp.Equal(pdu, dpdu) {
Yeah true. For that simple case we could definitely use `reflect`. However, it is more interesting for the line below `cmp.Diff`. However, I can also change that.

2021-01-14 19:26 UTC, gq0 commented on rtuclient_prop_test.go
> +		if !cmp.Equal(pdu, dpdu) {
This package is pretty useful. But just for this, it is a little too much 😂 Would be great if you can remove it. Many thanks for the test in general 👍🏻

2021-06-22 15:33 UTC, gq0 approved these changes
I guess the vendoring changed inbetween.

2021-06-22 16:00 UTC, frzifus approved these changes

2021-11-08 06:29 UTC, andig commented
What‘s missing to get this PR merged?

2021-11-08 07:37 UTC, guelfey commented
@andig basically just adjusting to the switch to go.mod that we did in the meantime

2021-11-08 07:52 UTC, andig commented
@jhedev would you kindly follow up? If not I'll try to take a look soonish.

2021-11-12 14:15 UTC, jhedev commented
@andig thanks for bring this back to life :) I'm pretty busy with other stuff right now. but I'll try to find time. If you're faster, feel free to take over.

2021-11-12 15:36 UTC, andig commented
@jhedev I think all you need is a `git rebase` plus `go mod tidy`. Tried to do that in https://github.com/grid-x/modbus/pull/41 but without much luck in linking that to your pr.

2021-11-13 13:44 UTC, jhedev commented
@andig thanks for the hint. I did the rebase and forced pushed again. 

re `cmp`. I'm not only using the `Compare` but also the `Diff` method. Happy to replace it but I still think it is a useful dependency.

2021-11-13 16:43 UTC, andig commented
> Happy to replace it but I still think it is a useful dependency.

I wouldn't mind, especially as it's test-only.

@guelfey good to go?

2021-11-13 16:50 UTC, andig commented
@jhedev if `go-cmp` remains a blocker you could use `reflect.DeepEqual` and replace the diff by "expected/got". It's a small helper during testing when an error actually occurs, but nothing absolutely required imho.

2021-11-13 18:39 UTC, guelfey approved these changes

2021-11-13 18:40 UTC, merged